In [3]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[0]

1

In [9]:
flat[3]

4

In [10]:
flat[3:6]

array([4, 5, 6])

In [11]:
flat[:5]

array([1, 2, 3, 4, 5])

In [12]:
flat[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [ ]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [16]:
b = flat[3:7]

In [17]:
b

array([4, 5, 6, 7])

In [18]:
b[0] = 444444

In [19]:
b

array([444444,      5,      6,      7])

In [20]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [ ]:
arr = np.array([1,54,5,7,47,98,9])
arr[[1,4,6]]# fancy indexing

array([54, 47,  9])

In [24]:
arr[arr>3]

array([54,  5,  7, 47, 98,  9])

In [25]:
arr[arr>20]

array([54, 47, 98])