In [16]:
#python zip explained
l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [ ]:
#using python lists
import numpy as np
import time

size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()

print(end - start)

0.0688021183013916


In [15]:
#using numpy arrays
import numpy as np
import time
size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.02148604393005371


In [13]:
l1 = [1,2,4]

In [6]:
l2 =[6,7,8]

In [8]:
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [1]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [2]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes
